### ISSUE TITLE
Could not find FFMPEG.

### ISSUE THREAD

**Issue by ln67** [anrayliu/pyvidplayer2#11]
Hello I used anaconda and I try  your examples and i have this error "FileNotFoundError: Could not find FFMPEG. Make sure it's downloaded and accessible via $PATH.". I downlaod FFMPEG 6.1 but it still doesn't work. Can you help me ?

**Comment by anrayliu** [comment]
Hello,

If you open cmd and type ffmpeg, does it show up?

**Comment by ln67** [comment]
no it's doesn't appair

**Comment by anrayliu** [comment]
That means ffmpeg is not accessible by pyvidplayer2. You probably downloaded it, but you didn't add it to PATH. Go to where you downloaded ffmpeg, go to the bin folder, and copy the path. Then follow the instructions here: https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/. Once you are done, ffmpeg should appear when you type it in the cmd. Try it and let me know if you need further help.

**Comment by ln67** [comment]
I don't find the bin folder in the ffmpeg folder 
![Capture d'écran 2023-12-21 165800](https://github.com/anrayliu/pyvidplayer2/assets/150193501/9cb0e2cb-abcb-4971-b8a6-0be99934d58a)

**Comment by anrayliu** [comment]
Go to this website: https://www.ffmpeg.org/download.html. Press windows, build from gyan.dev, then download ffmpeg-git-essentials.7z. It looks like you downloaded the source code instead of a build.

**Comment by PizzaPost** [comment]
I have the same issue but when I type ffmpeg in the console I get this:

ffmpeg version 2024-06-06-git-d55f5cba7b-full_build-www.gyan.dev Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 13.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libxevd --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxeve --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-ffnvcodec --enable-libvpl --enable-nvdec --enable-nvenc --enable-vaapi --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      59. 21.100 / 59. 21.100
  libavcodec     61.  6.100 / 61.  6.100
  libavformat    61.  3.104 / 61.  3.104
  libavdevice    61.  2.100 / 61.  2.100
  libavfilter    10.  2.102 / 10.  2.102
  libswscale      8.  2.100 /  8.  2.100
  libswresample   5.  2.100 /  5.  2.100
  libpostproc    58.  2.100 / 58.  2.100
Universal media converter
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'

**Comment by anrayliu** [comment]
Refer to https://github.com/anrayliu/pyvidplayer2/issues/30
