### ISSUE TITLE
Wrap importing of VideoTkinter

### ISSUE THREAD

**Issue by dtcooper** [anrayliu/pyvidplayer2#13]
Since not all Python installations have the `tkinter` module, I recommend wrapping the importing of `VideoTkinter` in a try/except, for example, in `pyvidplayer2/__init__.py`,

```python
try:
    import tkinter
except ImportError:
    pass
else:
    from .video_tkinter import VideoTkinter
```

Thanks for the great library!

**Comment by anrayliu** [comment]
Thanks for this. I will patch it in the coming days.
