### ISSUE TITLE
Can't install with pip under python 3.12 but it works with manual installation (spoiler in description)

### ISSUE THREAD

**Issue by mentat51** [anrayliu/pyvidplayer2#21]
pygame-ce 2.4.0 (SDL 2.28.5, Python 3.12.2)
{'pyvidplayer2': '0.9.12', 'ffmpeg': '6.1.1-essentials_build-www.gyan.dev', 'pygame': '2.4.0'}

If I try pip install pyvidplayer2, I got this in the numpy install : 
ModuleNotFoundError: No module named 'distutils'

as distutils have been removed from python, it's normal.

I have tried to change the requirements, like this (With the last version of numpy and with pygame-ce) : 
numpy
opencv_python
pygame-ce
pysubs2
PyAudio

and I can run all the examples with pyvidplayer installed from sources.

pip install this packages versions : 
Package       Version
------------- --------
numpy         1.26.4
opencv-python 4.9.0.80
pip           24.0
PyAudio       0.2.14
pygame-ce     2.4.0
pysubs2       1.6.1

Very good library, thanks !

**Comment by anrayliu** [comment]
Hi, 
Sorry for the super late reply. You are correct, the numpy version does cause an install error. The next patch will fix this. Thanks for telling me!

**Comment by anrayliu** [comment]
Version 0.9.14 fixes this problem.
