### ISSUE TITLE
Pyglet fullscreen mode looses focus because of ffmpeg process window

### ISSUE THREAD

**Issue by derUli** [anrayliu/pyvidplayer2#22]
When I play a video in my pyglet app, it opens a terminal window which immediately closes again but steals the focus from my pyglet app.

Playback works fine but I have to call window.activate() to focus my game window again after starting the playback.

This won't happen if I run my game from PyCharm but only when I run my game as a freeezed executable.
I think this happens because the freezed executable is a Win32GUI app.

**Comment by anrayliu** [comment]
If you compiled your exe using pyinstaller, did you use the --noconsole command?

**Comment by anrayliu** [comment]
Alright, then I will close this if there are no more problems.
