### ISSUE TITLE
 Implement adaptive window size

### ISSUE THREAD

**Issue by EvenYeah** [anrayliu/pyvidplayer2#24]
how to implement a function, that is by clicking the block icon at the upper right corner, it will do a full screen playback?

**Comment by anrayliu** [comment]
Hello, as shown in the pygame documentation (https://www.pygame.org/docs/ref/display.html), you can use ```pygame.display.set_mode``` or ```pygame.display.toggle_fullscreen``` to make your window fullscreen. Then, you can use the ```resize(size)``` method on your video to change it to the new fullscreen size.
