### ISSUE TITLE
Not a WAVE file

### ISSUE THREAD

**Issue by GaelHF** [anrayliu/pyvidplayer2#27]
I am trying to run this code with pyvidplayer2

studio = Video("assets/Videos/studio.mp4")
while studio.active:
    if studio.draw(screen, (0, 0), force_draw=False):
        pygame.display.update()
    pygame.time.wait(16)
pygame.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))

But I always get that the file is not a wave file.

**Comment by anrayliu** [comment]
Ensure that ffmpeg is installed and working properly. Make sure it is ffmpeg.exe that can be accessed, not ffplay or ffprobe.

**Comment by GaelHF** [comment]
.
