### ISSUE TITLE
Subtitles disappear after video.stop()

### ISSUE THREAD

**Issue by leandromacrini** [anrayliu/pyvidplayer2#28]
I'm implementing a slideshow software that continuously loops between some images and videos and I'm having a strange behavior:

if I block a video with the stop() function and then relaunch it with the play() function once every two times, the subtitles are not shown.

permanently: subtitle ok, subtitle disappeared, subtitle ok, subtitle disappeared and so on...

i'm on windows, using last pygame version

**Comment by leandromacrini** [comment]
I have found a workaround:

loop:
   video.stop()
   ...
   video.restart()
   video.play()

It now shows the subtitles at every loop.

**Comment by anrayliu** [comment]
Sorry for the late response, there's a new update coming in about 2 weeks that will fix this issue. Thanks for reporting!
