### ISSUE TITLE
More of a question: swapping between videos

### ISSUE THREAD

**Issue by CapnMittens** [anrayliu/pyvidplayer2#3]
Hi there!

I'm trying to use this code to play one of a library of .mp4 files. 
I was wondering if it's possible in a while loop to change the video being played based on an input (say a keyboard press)
This seems like it'd be easy, but maybe I'm misunderstanding what's going on under the hood that might be limiting this.

**Comment by CapnMittens** [comment]
Something I tried is of this form wherein pressing y will close the currently playing video and play the new video but there's a bit of lag in doing this. Wondering if there's a better way

if event.key == pygame.K_y:
    guest_video.close()
    guest_video = Video(filenames[1])

**Comment by CapnMittens** [comment]
Awesome! Thanks for the quick response. I'll try that out in the meantime, but excited for the update

**Comment by ree1261** [comment]
Hello again, I just released v0.9.6. Take a look at this code.
```
import pygame
from pyvidplayer2 import VideoPlayer, Video

win = pygame.display.set_mode((1280, 720))


vid = VideoPlayer(Video(r"resources\clip.mp4"), (0, 0, 1280, 720), loop=True, interactable=False)

vid.queue(Video(r"resources\ocean.mkv"))
vid.queue(Video(r"resources\birds.avi"))


while True:
    events = pygame.event.get()
    for event in events:
        if event.type == pygame.QUIT:
            vid.close()
            pygame.quit()
            exit()
        elif event.type == pygame.KEYDOWN and event.key == pygame.K_SPACE:
            vid.skip()
    
    pygame.time.wait(16)
    
    vid.update(events)
    vid.draw(win)
    
    pygame.display.update()
```
Here's the gist of what's happening. VideoPlayer is a container for videos. You can add to its queue with the ```queue``` method. As might guess, it'll play each video from the queue until everything has been played. You can use the ```skip``` method to prematurely end a video and move onto the next one. ```loop=True``` ensures that nothing is removed from the queue, allowing you to cycle the entire queue over and over again. If you don't want this, simply remove this argument. ```interactable=False``` disables the built-in gui that VideoPlayer comes with. The currently playing Video object can also be accessed via the ```video``` attribute. All this information and more can be found on the documentation page located in the repository. 

I'll leave this issue open for now until you've confirmed that this works. If you need anything else, just holler!

**Comment by CapnMittens** [comment]
Very nifty! Yep, this is what I was looking for and works better than the above method I was trying. There's still a tiny lag, but for my purposes, I think this runs really well, and it's super simple. 

One last question, is there a way for me to start a video at a particular timestamp/frame? I think I remember reading somewhere in the repo that this is possible

**Comment by CapnMittens** [comment]
Oh also, is it possible to pick a particular video in the queue rather than skipping just the next one

**Comment by ree1261** [comment]
Hmmm. These are actually some simple but surprisingly difficult questions for my implementation of a queue. Looks like I'll have to release another patch. Nevertheless, these are invaluable ideas to improving my library. Be back soon!

**Comment by ree1261** [comment]
Here are some temporary suggestions.

The VideoPlayer operates off of the ```queue_``` list. When it needs a new video, it'll take the first item from that list. Knowing this, you can bring the video you want to the front, and then call ```skip```.

```
def skip_to(player, index):
    vid = player.queue_[index]
    player.queue_.remove(vid)
    player.queue.insert(0, vid)
    video_player.skip()
```
Keep in mind, the currently playing video is not in the queue. This means the next video to play will be the first video in the queue. Knowing this, you can call the ```seek``` method before ```skip```.
```
def change_time(player, time):
    player.queue_[0].seek(time)
    player.skip()
```
The docs here goes into more detail on the skip method.

https://github.com/ree1261/pyvidplayer2/blob/main/documentation.md#:~:text=position%20in%20seconds.-,seek,-(time%2C%20relative%3DTrue

**Comment by CapnMittens** [comment]
Funny, I also just thought of that skip workaround. And the seek should work too!
I will note that there is certainly some lag between skips with the seek, but I think it functionally works as a suitable workaround

Thanks for such quick responses on this!

**Comment by ree1261** [comment]
Skipping unfortunately does involve a lot of lag, since it has to find new video frames and load new audio chunks. You can reduce the lag by decreasing the chunk_size attribute to something really small like 10 seconds. Read more here: https://github.com/ree1261/pyvidplayer2/blob/main/documentation.md#:~:text=from%20should%20work.-,chunk_size,-%2D%20How%20much%20audio
