### ISSUE TITLE
Ideal video settings to avoid lag and errors?

### ISSUE THREAD

**Issue by kurtvinci** [anrayliu/pyvidplayer2#31]
Hey! I have a few quick questions. 

I'm using a video that plays at 60fps, but after importing, it plays back at what feels like 30fps. It's the type of video that has flickering electric animation, kinda like in DBZ. Using this context, it's noticeable and loses some of its "oomph". The dimensions are 480 x 270, and I've experimented with different bit rates and other export options, trying both VBR and CBR. I've also tried different video file types. The duration is 10 seconds. Are there any sort of best practices to keep in mind for video export settings so that the playback is smoother with pyvidplayer2?

Also, I tried using an animated GIF, settling for its maximum frame rate of 50 (in the preview in Premiere it still had the flickering effect I'm trying to keep), but I get numerous audio errors when importing this file type. Is there a line of code that communicates that there is no audio, hopefully fixing these errors?

One final question. I would like to have this video _**automatically**_ loop, and _**seamlessly**_. The code provided in the other thread about looping does not help with this. I have to either move my mouse or click to get the video to loop. When using the player option, it loops,  but not seamlessly. Is there a solution to this problem, or is automatic and seamless looping not possible at the moment?

If anyone could answer I'd greatly appreciate it. Thanks!

**Comment by anrayliu** [comment]
Sorry for the late response. If you're still working on it, have you tried changing the chunk values when initializing the video? You can look at the documentation for more details. I would go ahead and try chunk_size=5 or even 1 to see if it helps with the seamlessness. Also are you able to use the videoplayer's built in looping feature?

**Comment by anrayliu** [comment]
Version 0.9.14 added a looping demonstration in the examples folder that may be what you want. I have optimized looping in the video player class to be as seamless as pyvidplayer2 can achieve. Hopefully it's good enough. Good luck on your project!

**Comment by anrayliu** [comment]
The fps problem is currently being fixed.

**Comment by anrayliu** [comment]
Version 0.9.15 fixes the frame rate problem.
