### ISSUE TITLE
Throttling coming to yt-dlp users reportedly

### ISSUE THREAD

**Issue by Poikilos** [anrayliu/pyvidplayer2#40]
Maybe turn off yt-dlp by default or have a "force" arg required.
- <https://www.reddit.com/r/youtubedl/comments/1c4e3y0/is_it_possible_to_be_permabanned_from_youtube_for/>
- https://github.com/yt-dlp/yt-dlp/issues/10085

**Comment by anrayliu** [comment]
Yt-dlp is already not installed by default. The `youtube` argument also has to be set to `True` manually for yt-dlp to activate as there is no automatic detection.

**Comment by Poikilos** [comment]
Ok, that seems to be all to be done for now, thanks.
