### ISSUE TITLE
Syntax error with pyvidplayer2

### ISSUE THREAD

**Issue by joseph-kimm** [anrayliu/pyvidplayer2#41]
There were not issues with the library till last week, but now there is an error relating to import.

File "C:\Users\user\Downloads\AI_CU-main\AI_CU-main\ai_cu_env\Lib\site-packages\pyvidplayer2\video.py", line 219
    p = subprocess.Popen(f"ffprobe -i {"-" if self.as_bytes else self.path} -select_streams v:0 -show_entries packet=pts_time -loglevel {FFMPEG_LOGLVL} -print_format json", stdin=subprocess.PIPE if self.as_bytes else None, stdout=subprocess.PIPE)
                                        ^
SyntaxError: f-string: expecting '}'

**Comment by anrayliu** [comment]
Hi, I was just about to respond to this, but you closed it? Did you end up fixing the problem?

**Comment by anrayliu** [comment]
Regardless, your issue actually made me realize there was a compatability issue with older Pythons, as they did not support string quotations inside f-strings. That has been fixed in v0.9.21, and that should also fix your problem in case you still have it.
