### ISSUE TITLE
Can't stream YT videos in VideoPlayer class

### ISSUE THREAD

**Issue by Kekulism** [anrayliu/pyvidplayer2#43]
The VideoPlayer class seems to be hardcoded to only work with paths to local videos. I really like the Queue system that the VideoPlayer class has but my project can't work unless the VideoPlayer class can stream YouTube videos. If you could add support for this, I would be very grateful.

**Comment by anrayliu** [comment]
Sure thing, it's about time anyway I brought the VideoPlayer class up to date with the rest of the library. I'll give you an update when I have time.

**Comment by anrayliu** [comment]
Hey so it turns out you can indeed queue youtube videos in the current version.
Just use
```
player.queue(Video("https://www.youtube.com/video", youtube=True))
```
As a reminder, you can queue preloaded Video objects instead of just paths.

**Comment by anrayliu** [comment]
Closing this for now. Let me know if it's not working, and I'll reopen it.
