### ISSUE TITLE
Compatibility with Audio Tracks? (Specifically YouTube)

### ISSUE THREAD

**Issue by Kekulism** [anrayliu/pyvidplayer2#45]
My last issue got worked out fine (thank you for that by the way), but now I've run into a more pressing issue relating to streaming YouTube videos. I've recently noticed that some channels on YouTube have been given access to add multiple audio tracks to their videos for dubbing in different languages. This is a great feature, but it seems to be causing issues with streaming these videos in pyvidplayer2. When I tried putting [this video](https://youtu.be/bKjfw77cxeQ?si=DkRgYaEu0tEaWf3F), for example, in the program, it played the video in some other language I didn't recognize by default.

![NVIDIA_Share_hqI30kHvI9](https://github.com/user-attachments/assets/08de1082-d1a0-464d-a1c4-99c02620d339)

Since audio track selection and switching are already implemented for local videos, it would be really helpful to have that functionality implemented for YouTube video streaming as well.

**Comment by anrayliu** [comment]
Thanks for telling me, I didn't know Youtube had this feature. Luckily, this is an easy problem to solve, but you'll have to wait a few days because I am quite busy right now. As a side note, how are you liking the library? Have you tried with local videos? Just asking for feedback.

**Comment by Kekulism** [comment]
I haven't tried audio track switching yet, but the library is fantastic and I really appreciate that it exists. For my purposes it's great, I just gotta get better at programming so I can utilize it efficiently

**Comment by Kekulism** [comment]
While I'm at it, I'm having a different issue related to audio, I want to see if I can specify a specific audio device for the videos to play on, but I'm not quite sure how to do that. Is there a feature for that?

**Comment by anrayliu** [comment]
I actually did have someone add a device selector some time ago, but it's only for the backend. I will look into making it available to users.

**Comment by Kekulism** [comment]
One more thing, sorry I don't mean to give you a bunch of work to add to your pile but a bit ago you said that you would look into updating the VideoPlayer class to work better with the rest of the code. Whenever you get the time to do that, and if it's possible, could you look into adding support for Pyglet with the VideoPlayer class? I'm thinking I might wanna switch over to that so that my project works better with async code, getting a lot of headaches related to not having async in my project

**Comment by Kekulism** [comment]
Nevermind, I figured out a good way around the headaches I was describing. I was trying to find a way for my Pygame code to be able to run a separate async function that was able to handle the queueing of new videos into the VideoPlayer class. That way the currently playing video wouldn't stutter visually when the program loaded the queued video. I got that working, now it queues in the background with no lag, which is fantastic for my purposes. 

Still trying to get some other issues sorted out with YT-DLP though, it seems like all YouTube videos with enhanced premium bitrates don't properly play their video at all (but they still play their audio) due to some download issues, and sometimes they'll even crash the Pygame window (but the audio will still play). Right now I'm trying to see if I can use a YT-DLP conf file to solve that issue with the downloads. I feel like this isn't an issue with pyvidplayer2 necessarily, so I wont ask more of you than I already have

**Comment by anrayliu** [comment]
> it seems like all YouTube videos with enhanced premium bitrates don't properly play their video at all (but they still play their audio)

This is mostly likely because the program crashed but pyaudio is still playing the audio in a thread. If this is annoying, you can use the `use_pygame_audio=True` parameter instead of pyaudio, which will close whenever the program does as well.

As for the actual issue, I don't even have premium, so yeah I won't be of much help there.

**Comment by anrayliu** [comment]
Hey sorry for the late update, but v0.9.24 is now published and contains the features you have requested. Refer to preferred_language_demo.py and audio_devices_demo.py in the examples folder for instructions. Let me know if you encounter any bugs or issues. I'll leave this thread open for a little while until you confirm everything has been resolved. Cheers!

**Comment by Kekulism** [comment]
I'm also sorry for the late update, everything works great! Thank you for implementing these changes. Since you mentioned it though, I did occur to me that I'm not sure if YouTube subtitles are implemented in this library yet. I've tried to find a way to do it and it seems like it only supports local subtitle files. I'm also unsure if there's an option to toggle subtitles on and off while playing a video, but I could be wrong about that. I could also be wrong about the former as well, but I thought I'd mention it just in case. Having YouTube subtitles working would be a great help for my project

**Comment by anrayliu** [comment]
Good to hear that it works. Subtitles are actually the next item on the list to improve, and pulling subtitles from Youtube was indeed already a planned feature. However, it seems like this issue is digressing, so I've opened a new issue about subtitles: https://github.com/anrayliu/pyvidplayer2/issues/46. 

That said, to tide you over until the updates come, have you tried using some library to download Youtube subtitles before a video is played? And to toggle subtitles, you can use the very hacky solution of setting ```video.subs = None```.
