### ISSUE TITLE
Specifying audio_index argument makes YouTube videos break

### ISSUE THREAD

**Issue by Kekulism** [anrayliu/pyvidplayer2#47]
Sorry again for the amount of stuff I'm posting here, but this time it's an actual problem and not just a feature request. I was testing out the new audio_index argument for Videos, and noticed that it breaks YouTube videos pretty much entirely. The audio doesn't play for them, and the video becomes a slideshow of one frame per every 20 seconds or so. This doesn't happen when I tested it with local videos, but it consistently occurred when trying to stream from YouTube.

**Comment by anrayliu** [comment]
Which videos are you having issues with?

**Comment by Kekulism** [comment]
Any and all YouTube videos it seems like. As long as the audio_index is not None, and I try to play a YouTube video, it breaks. Does it work for you? It might be an issue with my project specifically but it's hard to tell. There isn't any errors or anything output in my console and again, it only occurs when the audio_index is specified.

**Comment by Kekulism** [comment]
I tested audio_indexes by just running the example file with a youtube video, and it works there. Works with both the .preview() and the traditional video_player loop. Strange. Gotta figure out why that happens specifically in my main project. There's a lot of moving parts in the code of it so it's hard for me to pinpoint the cause of stuff sometimes. I'll leave this open in case you have any suggestions for what you think might be causing the issue to occur, and I'll keep looking into it.

**Comment by Kekulism** [comment]
Okay, I figured it out. I've been using this function to be able to grab the correct audio index based on a device name input. Since the audio index list changes frequently and audio indexes don't stay the same audio device, this was required for my code.

`def find_device(name, api=0):
    # Loop through the list of devices to find a match
    devices = []
    if name is None:
        return None
    for device in sounddevice.query_devices():
        if name in device['name']:
            devices.append(device)
    print(devices)
    for d in devices:
        if api is not None:
            if d['hostapi'] == api:
                return d['index']
        else:
            return d['index']
    raise ValueError(f"Device '{name}' with API '{api}' not found")`
    
Now, I had the api argument set to 1, because i mistakenly thought that was the value for MME. It wasn't, the value for MME is 0, and once I set it to that and tried playing a youtube video with an MME audio device index, it works. 

So the issue here is that YouTube videos become unwatchable when the audio index is set to a device with a host api that isn't MME. At least, that issue consistently occurred for me. I dunno if it's just a me issue with audio device knowledge, maybe I should have known that I shouldn't use any other api besides MME, but regardless it confused me a lot. My problem is solved, but to help others who may come across this in the future I think I'd put a warning to make sure that your audio device is MME or something

**Comment by anrayliu** [comment]
Sounds great, glad you're issue is solved.
