### ISSUE TITLE
Show UI only on hover mouse over borderless video

### ISSUE THREAD

**Issue by project-owner** [anrayliu/pyvidplayer2#48]
If I change the video with border in this example:
https://github.com/anrayliu/pyvidplayer2/blob/12ba700fe63af264b6a24421491901cf0c22c6ce/examples/videoplayer_demo.py#L12
to borderless video:
vid = VideoPlayer(Video(r"resources\ocean.mkv"), (0, 0, 1124, 868), interactable=True)
then UI stays on screen forever. Is it possible to show UI only when mouse is over the player screen for borderless video?
Thanks!

**Comment by anrayliu** [comment]
The video player update method takes an argument called show_ui. It is a boolean that can be used to force the ui to show or hide. You can use a library like pywin32 to get global mouse coordinates and calculate if they are on top of the pygame window, and then pass that as show_ui. You can read more about the videoplayer in the docs here: https://github.com/anrayliu/pyvidplayer2/blob/main/documentation.md
