### ISSUE TITLE
can I use a different approach without directly downloading ffmepg?

### ISSUE THREAD

**Issue by frankiephs** [anrayliu/pyvidplayer2#5]
So I was planning on sharing it to my friends, I was wondering if I can send them this directly without them downloading ffmepg because I am planning to convert my pygame to exe

**Comment by ree1261** [comment]
Hello,

Unfortunately, you do have to have ffmpeg. However, you can distribute ffmpeg with your projeect so your friends won't have to download it themselves. When you download ffmpeg, there should be 3 exes in the bin folder. Copy ffmpeg.exe over to your game directory and pyvidplayer2 should be able to locate it.
