### ISSUE TITLE
Playing youtube streams directly

### ISSUE THREAD

**Issue by denizsincar29** [anrayliu/pyvidplayer2#8]
Hello. I've an awesome idea. What if we could play youtube vids straight with this app? I'm makin' a simple youtube player for the blind and, well, good if it would not be only for blind but also for sighted.

**Comment by ree1261** [comment]
Hello,

This is is an awesome idea! I've tried this in the past, but gave up on it because of difficulties. If you want, I would be more than happy to collaborate on this.

**Comment by DOODLEDO3946** [comment]
I was able to modify the Video class to be able to handle youtube videos by getting the streams for video and audio which can be used with opencv and ffmpeg. It seems yt_dlp returns different streams for video and audio
`            import yt_dlp
            with yt_dlp.YoutubeDL() as ydl:
                info = ydl.extract_info(path, download=False)
                self.name = info["title"]
                for format in info["formats"]:
                    if format["video_ext"] != "none":
                        self.path = format["url"]
                    
                    elif format["audio_ext"] != "none":
                        self.audio_path = format["url"]`

**Comment by anrayliu** [comment]
> I was able to modify the Video class to be able to handle youtube videos by getting the streams for video and audio which can be used with opencv and ffmpeg. It seems yt_dlp returns different streams for video and audio
> 
> ```
> import yt_dlp
> with yt_dlp.YoutubeDL() as ydl:
>     info = ydl.extract_info(path, download=False)
>     self.name = info["title"]
>     for format in info["formats"]:
>         if format["video_ext"] != "none":
>             self.path = format["url"]
>         elif format["audio_ext"] != "none":
>             self.audio_path = format["url"]
> ```

Thanks for the help! This feature still needs some time, as there are still a lot of bugs and issues.

**Comment by anrayliu** [comment]
Version 0.9.15 allows streaming from Youtube. Check out ```youtube_streaming_demo.py``` in the examples folder.
